language: python
dist: trusty
sudo: false
python:
    - "3.5"
    - "3.6"
    - "pypy3.5"
matrix:
    fast_finish: true
install:
    - pip install -r requirements-dev.txt
script:
    - make test_coverage
    - make flake8
after_success:
    - coveralls
