language: python
python:
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3.3-5.2-alpha1"
matrix:
    fast_finish: true
install:
    - pip install -r requirements-dev.txt
script:
    - make test_coverage
    - make flake8
after_success:
    - coveralls
